### ISSUE TITLE
Process only active entity.

### ISSUE THREAD

**Issue by Partysun** [PDeveloper/hxE#4]
Hello, @PDeveloper 

Entity has isActive parameter, but System doesn't check active entity or not in processing function.
Now isActive doesn't have any logic in hxE.
Maybe, you pass it.

Thank you,

**Comment by PDeveloper** [comment]
That is correct! : D
This was meant to be implemented, but as development went on, the isActive parameter isn't really necessary - it's the same as if an entity exists in the first place or not. (If you want isActive = false, destroy the entity, and isActive = true, just create it again)

But I'll accept pull requests for adding the functionality. Problem is that it's hard to pinpoint a good place to do it - duplicate code in EntityProcessingSystem and IntervalProcessingSystem, or somehow integrate it in the EntitySystem level - maybe an additional constraint is that entity.update() should be called after setting isActive, and then in the EntitySystem::updateEntity(Entity) function, the first thing it checks is if the entity is active or not. If it's isActive = false, remove it from the system (if it has it) etc., otherwise process normally.
